backend:
  name: github
  repo: nimbarkvisualshub1-boop/Aviart05
  branch: main
  base_url: https://silver-shortbread-9df8fe.netlify.app
  media_folder: "uploads"
  public_folder: "/uploads"

collections:
  - name: "projects"
    label: "Portfolio Projects"
    folder: "content/projects"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Category Badge", name: "badge", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Artwork Image", name: "image", widget: "image"}
